version: '3.9'

services:
  backend:
    build: ./backend
    container_name: billing_backend
    ports:
      - "8080:8080"
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pfl_docker_billing
      FRONTEND_URL: ${FRONTEND_URL}
    # убираем depends_on, если база данных запускается отдельно!

  frontend:
    build: ./frontend
    container_name: billing_frontend
    ports:
      - "5173:80"