version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: billing_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pfl_docker_billing
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: