version: '3.9'

services:
  backend:
    build: ./backend
    container_name: billing_backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pfl_docker_billing
      DB_PORT: 5432
  postgres:
    image: postgres:16-alpine
    container_name: billing_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pfl_docker_billing
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: