version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: billing_backend
    ports:
      - "8080:8080"

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: billing_frontend
    ports:
      - "5173:80"