name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend Go tests
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run backend tests
        run: |
          cd backend
          go test ./... -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: rustemsharipov/pfl_docker_billing_backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: rustemsharipov/pfl_docker_billing_frontend:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull rustemsharipov/pfl_docker_billing_backend:latest
            docker pull rustemsharipov/pfl_docker_billing_frontend:latest

            docker stop billing_backend || true
            docker rm billing_backend || true
            docker stop billing_frontend || true
            docker rm billing_frontend || true

            docker run -d --name billing_backend \
              --network host \
              -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
              -e DB_HOST=localhost \
              -e DB_USER=postgres \
              -e DB_PASSWORD=postgres \
              -e DB_NAME=pfl_docker_billing \
              -e FRONTEND_URL=http://${{ secrets.SERVER_HOST }}:5173 \
              rustemsharipov/pfl_docker_billing_backend:latest

            docker run -d --name billing_frontend \
              -p 5173:80 \
              rustemsharipov/pfl_docker_billing_frontend:latest